# Numpy package

In [ ]:
# !pip install numpy

In [6]:
import numpy as np

In [7]:
lst = [1,2,4]

In [8]:
array = np.array(lst)

In [9]:
type(array)

numpy.ndarray

In [14]:
ar = array**2

In [15]:
ar

array([ 1,  4, 16], dtype=int32)

In [16]:
len(lst)

3

In [17]:
ar.size #getting size of the array

3

In [18]:
ar.shape

(3,)

In [19]:
lst = [[1,2],
      [3,4],
      [5,6]]

In [24]:
len(lst)

3

In [20]:
np_lst = np.array(lst)

In [22]:
type(np_lst)

numpy.ndarray

In [23]:
np_lst.size

6

In [25]:
np_lst.shape

(3, 2)

In [26]:
a = np.array([1,2,3,4])

In [27]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [28]:
a*2

array([2, 4, 6, 8])

In [29]:
a.sum()

10

In [32]:
a.mean()

2.5

In [33]:
a.std()

1.118033988749895

In [34]:
a.var()

1.25

In [36]:
a = np.array([[1,2,3],
              [4,5,6]])

In [37]:
a.shape

(2, 3)

In [38]:
a.sum(axis=1)

array([ 6, 15])

In [39]:
a.sum(axis = 0)

array([5, 7, 9])

In [43]:
a = np.ones((3,2))

In [44]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [47]:
a = np.identity(4)

In [48]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
a = np.random.randint(1,10,(3,4)) 

In [51]:
print(a)

[[2 8 1 5]
 [9 2 2 3]
 [5 7 1 3]]


In [52]:
a.shape

(3, 4)

In [53]:
b = np.random.randint(1,10,(3,4)) 

In [54]:
print(b)

[[3 1 6 5]
 [5 9 8 8]
 [3 4 8 1]]


In [55]:
c = a+b #linear agebra

In [56]:
print(c)

[[ 5  9  7 10]
 [14 11 10 11]
 [ 8 11  9  4]]


In [57]:
c = a*b

In [58]:
print(c)

[[ 6  8  6 25]
 [45 18 16 24]
 [15 28  8  3]]


In [59]:
c+1 #adds the number to all the elements

array([[ 7,  9,  7, 26],
       [46, 19, 17, 25],
       [16, 29,  9,  4]])

In [60]:
c*2

array([[12, 16, 12, 50],
       [90, 36, 32, 48],
       [30, 56, 16,  6]])

In [63]:
np.cos(3.14)

-0.9999987317275395

In [64]:
np.square(5)

25

In [66]:
a = np.random.randint(1,10,(2,3))

In [67]:
b  = np.random.randint(1,10,(3,2))

In [68]:
a

array([[5, 7, 9],
       [3, 4, 3]])

In [69]:
b

array([[4, 1],
       [5, 4],
       [5, 3]])

In [71]:
np.matmul(a,b)

array([[100,  60],
       [ 47,  28]])